# Define the minimum iOS version your app supports
platform :ios, '13.4'

# Use the path to your React Native project
require_relative '../node_modules/react-native/scripts/react_native_pods'

# Prepare React Native project
prepare_react_native_project!

# Define your app target
target 'Dr' do
  # Configure native modules
  config = use_native_modules!

  # Use React Native
  use_react_native!(
    :path => config[:reactNativePath],
    # Disable Flipper
    # :flipper_configuration => FlipperConfiguration.enabled,
    # Path to your app
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Define any additional targets here (e.g., for testing)
  target 'DrTests' do
    inherit! :complete
    # Pods for testing can be added here
  end

  # Post-installation configuration
  post_install do |installer|
    # React Native post-installation script
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
